### ISSUE TITLE
Uses a lot of CPU (and makes my lap hot)

### ISSUE THREAD

**Issue by adamrp** [biocore/emperor#164]
Using a lot of CPU when in use is probably expected, and I can accept that.  But when I'm not interacting with it, I think it should not be burning 80% of a core.  Maybe just a strict 30 frames-per-second cap on rendering would do the trick?  Or some logic to figure out when it needs to be updating the frame?

**Comment by squirrelo** [comment]
Fixed by #470. No more cooked laps or laptops!
