### ISSUE TITLE
Smarter rendering of the widgets (used to be memory degradation)

### ISSUE THREAD

**Issue by antgonza** [biocore/emperor#178]
~~When working with a lot of samples and a lot of columns, it seems that the performance degradates as you change between coloring columns. This is more noticeable when working with gradients. Maybe we need to force the cleaning of variables/objects??~~

**Comment by ElDeveloper** [comment]
We should be able to use something like [SlickGrid](https://github.com/mleibman/SlickGrid/wiki) for this purpose. This should make it such that widgets are lazily loaded.
