### ISSUE TITLE
Automate Creation of Multiple Screenshots

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/emperor#183]
If the `index.html` file is opened, the code should be able to generate multiple screenshots based on a metadata category.
- Opacity highlight.
- Color highlighting.
- Using the arrow that we currently have in place.

**Comment by Utopiah** [comment]
Could try using MESA but according to http://phantomjs.org/supported-web-standards.html they don't plan to work with that.

**Comment by ElDeveloper** [comment]
Thanks for the info!
