### ISSUE TITLE
silent error due to invalid mapping file

### ISSUE THREAD

**Issue by wdwvt1** [biocore/emperor#232]
If you have a mapping file with 2 header fields of `SampleID`, `make_emperor.py` will fail to produce an image output. The right-side menu won't be displayed and it will say '0/0' points. While its incumbent on the user to check their mapping file, it seems that perhaps this could fail more gracefully as no error is produced.

**Comment by ElDeveloper** [comment]
This should no longer be an issue with the current handling of metadata.
