### ISSUE TITLE
how to identify the two or more variables contributing to the cluster in PCoA plots using emperor

### ISSUE THREAD

**Issue by balageek** [biocore/emperor#275]
Hi,

we have a two seperate cluster in PCoA 3D plot and it seems like none of the variables(such as age, food habit, etc.. when used alone to visualize) couldnt explain the clear cluster and it might be due to the combined effect of the variables which makes that cluster. Is there any ways in emperor that we can include more than one or two variables to visualize the 3D plot in order to explain that cluster???

Any help will be very useful. Thanks in advance.

Bala

**Comment by ElDeveloper** [comment]
I'll close this, as @antgonza's suggestion would be implemented as part of #356
