### ISSUE TITLE
2D PCoA plot feature?

### ISSUE THREAD

**Issue by melisanahtar** [biocore/emperor#303]
Could you add a feature to display the PCoA plot in two dimensions, mostly for publication purposes? Some statisticians who I've shown my 3D plots to think it's incorrect to display three dimensions on a 2D piece of paper. They're also concerned that it enables you to potentially mask data points that don't fit in nicely with your clustering by fiddling with the orientation. I've been getting around this by carefully orienting the 3D plot to look two-dimensional, but it would be great if it could be a one-click feature. Thanks for your consideration!

**Comment by ozkurt** [comment]
It would be great if you can 2D plot feature. 3D is good when it is interactive, but for publication purposes we need 2Ds.
Thank you..
