### ISSUE TITLE
Scaled Gradient

### ISSUE THREAD

**Issue by jwdebelius** [biocore/emperor#311]
It would be awesome if, with continuous  or numerical data, the gradient took into account the total range, rather than just assuming the difference between two adjacent categories is the same.

For instance, if I have a sample taken at pH 2, a sample taken at pH 8 and four samples with pHs of 4.7, 4.9, 5.1, and 5.3, it would be nice if the gradient reflected the move extreme values.

**Comment by ElDeveloper** [comment]
It would be great to add the ability to perform transformations to the data, log transform would be the most important.

**Comment by ElDeveloper** [comment]
See also what ili does for scaling (related to #429).
