### ISSUE TITLE
Adjusting plotted PC# when using explicit axes feature

### ISSUE THREAD

**Issue by lkursell** [biocore/emperor#326]
Presently, if you are visualizing 1 explicit axis, Emperor limits you to looking at PC1 and PC2. If you are visualizing 2 explicit axes (lets say X and Y) you can only look at PC1.

However, being able to X, Y, PC2 in addition to X, Y, PC1 -> basically being able to chose the PC axes.

**Comment by ElDeveloper** [comment]
Thanks for reporting this issue! I'm adding this to the 0.9.6 milestone
as it is important for this feature to be available and there's no
reason why it shouldn't.
