### ISSUE TITLE
Click on points to reveal label

### ISSUE THREAD

**Issue by lkursell** [biocore/emperor#327]
Sometimes the cluster of points is too dense to distinguish an individual point's label when the labels are all turned on. Would be nice to be able to click on one point and have the label appear, perhaps at the bottom of the PCoA plot, like what happened in KiNG

**Comment by antgonza** [comment]
Agree, have you tried playing with the transparency of the points?

**Comment by lkursell** [comment]
That helps some, and with that + zooming the answer is eventually retrievable…though this is not pretty to look at:

**Comment by wasade** [comment]
This would be awesome but just so you're aware, it is potentially
challenging to implement. Hit boxes are surprisingly tedious to resolve and
may require data structure changes to put in place.

**Comment by lkursell** [comment]
No worries, and thanks for the insight, Antonio’s suggestion worked

**Comment by ElDeveloper** [comment]
:+1: on that this issue should be resolved! When I get some time I'll
try having a look and see how problematic this may be to implement.

**Comment by clozupone** [comment]
Hey, what is the current status of this issue? This is the one functionality that I really miss from KING. Particularly with a large dataset, it is nearly impossible to tell from labels what sample a point represents.

**Comment by rob-knight** [comment]
+1

**Comment by ElDeveloper** [comment]
@clozupone we are doing a major refactoring at the moment (see #405), I've added this feature request as part of the points that must be covered, more updates soon.
