### ISSUE TITLE
Name suggestions when there's a typo/error

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/emperor#329]
There are several options in the command line interface that refer to a header name in the mapping file, often times if the user makes a mistake and passes a header name that doesn't exist, the script errors and shows all the available headers which is not very helpful if you have a few dozen metadata categories. The proposed enhancement is to use [fuzzywuzzy](http://chairnerd.seatgeek.com/fuzzywuzzy-fuzzy-string-matching-in-python/) to find the closest match in the headers and suggest that instead. For example if the user entered `IDD_TYPE` and the existing categories were `['DOB', 'BARCODE', 'IBD_TYPE']`, the error message would print something like `Could not find 'IDD_TYPE', did you mean 'IBD_TYPE'`.

**Comment by Jorge-C** [comment]
I agree that would be very nifty!

There are several options in the command line interface that refer to a
header name in the mapping file, often times if the user makes a mistake
and passes a header name that doesn't exist, the script errors and shows
all the available headers which is not very helpful if you have a few dozen
metadata categories. The proposed enhancement is to use fuzzywuzzy
<http://chairnerd.seatgeek.com/fuzzywuzzy-fuzzy-string-matching-in-python/>
to find the closest match in the headers and suggest that instead. For
example if the user entered IDD_TYPE and the existing categories were ['DOB',
'BARCODE', 'IBD_TYPE'], the error message would print something like Could
not find 'IDD_TYPE', did you mean 'IBD_TYPE'.

—
Reply to this email directly or view it on GitHub
<https://github.com/biocore/emperor/issues/329>.

**Comment by ElDeveloper** [comment]
Metadata categories are no longer inputed or handled by Emperor, this would now be an issue for QIIME2, specifically here https://github.com/qiime2/q2cli/issues
