### ISSUE TITLE
numpy FutureWarning raised in emperor.format

### ISSUE THREAD

**Issue by jairideout** [biocore/emperor#330]
When running the jackknifed beta diversity command in the [QIIME 454 overview tutorial](http://qiime.org/tutorials/tutorial.html), the following warnings were raised within `emperor.format`:

```
$ jackknifed_beta_diversity.py -i otus/otu_table.biom -t otus/rep_set.tre -m Fasting_Map.txt -o jack -e 110
/Users/jairideout/.virtualenvs/qiime/lib/python2.7/site-packages/emperor/format.py:104: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if coords_low != None and coords_high != None:
/Users/jairideout/.virtualenvs/qiime/lib/python2.7/site-packages/emperor/format.py:104: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if coords_low != None and coords_high != None:
```

I have Emperor 0.9.5 and numpy 1.9.1 installed.

**Comment by ElDeveloper** [comment]
Thanks for catching this! When fixing this issue, we should also update .travis.yml to test with 1.9.0 and plan for a maintenance release as this will be something QIIME users will see and get worried/confused.

**Comment by jairideout** [comment]
:+1:
