### ISSUE TITLE
SVG files are not downloading

### ISSUE THREAD

**Issue by JTFouquier** [biocore/emperor#333]
SVG files are not downloading correctly right now.  All I can get is a PNG and I used to download the SVG.

Error below with the entire screen below being blank.

Thanks!

![screen shot 2015-01-26 at 11 08 37 pm](https://cloud.githubusercontent.com/assets/7920357/5914759/5c69d2f8-a5b0-11e4-8b51-4b0dc4b767c0.png)

**Comment by ElDeveloper** [comment]
Thanks for reporting this, would you mind telling us what version of
emperor you are using as well as the browser and version. Note that we
officially only support Google Chrome.

**Comment by JTFouquier** [comment]
Chrome Version 40.0.2214.91 (64-bit) (which is my default browser).  I cannot find a version number for Emperor.  I have always used the html link through the Qiime output.

**Comment by ElDeveloper** [comment]
Thanks, to get the emperor version you can do "head index.html" inside your output folder. Or you can do make_emperor.py --version 

Yoshiki Vázquez-Baeza

**Comment by JTFouquier** [comment]
Got it.  Emperor version 0.9.3

**Comment by ElDeveloper** [comment]
Got it, we fixed that issue a few versions ago, so you can update your version of Emperor or use the workaround in the first comment of this thread: https://github.com/biocore/emperor/issues/256

Yoshiki Vázquez-Baeza

**Comment by JTFouquier** [comment]
Oh, sorry about that.  I searched for "SVG files" and "downloading files"
in the issues and could not find anything. But the default search is set to
"open issues", so I should have changed that.

Thanks!

**Comment by ElDeveloper** [comment]
No problem, let us know if the problem persists!
