### ISSUE TITLE
pan option or center plot

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [biocore/emperor#334]
It seems as though the positioning of the entire plot could be improved by giving an option for the user to not only adjust orientation of it, but also to pan it (I often feel there is too much blank space above the plot).  Furthermore, the 'Recenter Camera' button could also center the three axis both horizontally and vertically in the black space.

**Comment by antgonza** [comment]
Have you tried clicking with the right button of the mouse (two
fingers click on a mac, depends on your configuration) and moving the
plot?

**Comment by ConstantinoSchillebeeckx** [comment]
My right click has been setup by pressing 'control' (I'm on a mac)

Panning works in Firefox but not in Safari nor in Chrome. I've checked with this example: http://emperor.colorado.edu/master/make_emperor/biplot/index.html

**Comment by antgonza** [comment]
AFAIK control has been set up for other uses on Chrome and Safari,
thus not working. Have you tried changing your config to use two
fingers?

**Comment by ConstantinoSchillebeeckx** [comment]
looks like I had to manually turn on 'secondary click' - all is well now!

Thanks for the support

**Comment by ElDeveloper** [comment]
Good to hear this was solved!
