### ISSUE TITLE
execute make_emperor.py from browser

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [biocore/emperor#335]
I've created a bash script that that invokes several QIIME scripts (beta_diversity.py, principal_coordinates.py) as well as the make_emperor script together so that I can easily prep PCOA plots given a biom and mapping file.  The script works well from the command line; I'm trying to implement a GUI front-end in a browser that will call this bash script and generate the PCOA plots from files provided through the GUI.

As it stands, the GUI is developed and the bash script is executed from the browser (through PHP).  All the QIIME scripts within the bash script run properly, however when execution gets to make_emperor.py it stops.  I'm running an apache web server on a linux ubuntu box and developing locally.

Is this a permissions issue? (things are run by www-data) What else could it be?

**Comment by ElDeveloper** [comment]
I can think of a few reasons that may be causing this problem in your
system:

- The machine runs out of memory and kills the subprocess. This seems
  very unlikely as I would expect beta_diversity.py or
  principal_coordinates.py to fail if this was the case.

- There's an error that's being raised during the execution of
  make_emperor.py and the output is not being captured/printed. Do you
  get an error message somewhere? Can you share the error and the
  command you are using?

- The permissions for the user running this process may not be
  sufficient for it to create folders and access the required resources
  in the emperor installation folder. make_emperor.py makes a copy of
  the resources located in emperor/support_files and saves them to the
  desired output directory.

Please let me know what you find!

**Comment by ElDeveloper** [comment]
Note that the workflows in QIIME call make_emperor.py through a
subprocess, so in principle this mechanism should work without a
problem.

**Comment by antgonza** [comment]
Note that it sounds like you are trying to implement some
functionality already added in: https://github.com/biocore/qiita ...

**Comment by ConstantinoSchillebeeckx** [comment]
I was able to find a workaround, although I'm not sure how happy I am about it.

I'm running apache as my 'standard ssh login user' instead of www-data by setting the option 'User matatu' in the apache2.conf file (where matatu is the standard login user).  With apache running as the other user, everything works just fine.  

I'm not super familiar with user permissions, so I'm not sure how to troubleshoot things with the www-data.

As far as logging errors, I'm not finding anything in the logs (but unsure if things are being logged properly).  The make_emperor command is the vanilla execution with a mapping file.

**Comment by ElDeveloper** [comment]
Were you able to verify that your apache user has access to the folder
containing emperor's required resources? Have you tried running
make_emperor.py as the apache user?

I'm closing this issue for now as you've found a workaround and the
problem seems to be unrelated with the codebase, however please reopen
it if you find a problem where Emperor might be the culprit.
