### ISSUE TITLE
When creating a legend using a painting that is continuous...

### ISSUE THREAD

**Issue by wasade** [biocore/emperor#336]
...it would be nice to have the gradient depicted in the legend, instead of representing the gradient as categorical.

**Comment by ElDeveloper** [comment]
The problem with this is that categories are not required to be
continuous when they are colored using a gradient. Think a discrete
metadata category (containing foo, bar, baz and spam) colored using the
continuous maps, what you would end up with is a colormap where you
could only really identify the colors for bar and spam.

A workaround would be to only provide the ability to create a gradient
when all the identified categories are numerical. I don't like this
solution, but I would like to hear what you guys think.

**Comment by wasade** [comment]
Possible to dump a gradient legend (ie just plot the colormap) when a
continuous colormap is in use? Could just then put the min/max values on
each end, or if non numerical, whatever the first/last items are

**Comment by ElDeveloper** [comment]
What about putting both the categorical breakdown and a colormap with
the first and last category value aligned to the top and bottom of the
rectangle with the colors.

**Comment by antgonza** [comment]
I think the easiest will be to have the gradient in an static high res
form either as part of the package, the repo or both so people can
simple use it in their own pics. Something like this:
http://reference.wolfram.com/language/guide/ColorSchemes.html

**Comment by ElDeveloper** [comment]
This is not a bad idea at all. I think having them as part of the
website would be the best. But I can see why we may want to have them be
part of each plot (those would be dynamically created).

**Comment by antgonza** [comment]
Yeah but that will imply a lot of work, which could be spent on
something else. The website will be the easiest and fastest.

**Comment by wasade** [comment]
+1 on just having them already available. Would be great to auto label, but
agree that is more annoying and time consuminv

**Comment by squirrelo** [comment]
This was solved by #456 , correct?

**Comment by ElDeveloper** [comment]
Yes, kinda, though we still need to add the "Save as SVG" functionality that now takes advantage of the existing colorbar and **just** saves it 😃
