### ISSUE TITLE
When creating a legend with different scaled spheres...

### ISSUE THREAD

**Issue by wasade** [biocore/emperor#337]
...it would be great if the legend included a section that had an example sphere and what piece of metadata it corresponded to. For instance, if treatment A is of a smaller size and treatment B is of a larger size, having the legend automatically explain this would be really awesome.

**Comment by ElDeveloper** [comment]
Just a note: since categories you use to color and scale can be
orthogonal to each other, this would imply writing a separate list with
"example" sphere sizes. Or maybe even a different file with this
information, thoughts?

**Comment by antgonza** [comment]
I think multiple files is fine. The files being created are based on
which selections have been actually changed.

**Comment by wasade** [comment]
Yes and agree

**Comment by ElDeveloper** [comment]
Closing this in favor of https://github.com/biocore/emperor/issues/634
