### ISSUE TITLE
Modernize codebase

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/emperor#342]
~~Add coveralls.~~
Add flake8/pep8 checks.
Remove `__version__`,`__author__` ... etc strings where possible.
Add BSD license header to all files.
Remove shebang from library files.

I'm tagging this issue as an easy fix, because the changes should be very simple, however it might take a while to do them all.

**Comment by ElDeveloper** [comment]
- [ ] @josenavas will work on sort.py and test_sort.py
- [ ] @mortonjt will work on biplots.py and test_biplots.py 
- [ ] @ElDeveloper will work on format.py and test_format.py
- [ ] @wasade filter.py and test_filter.py

-------

The following have been unclaimed yet:

- [ ] parse.py and test_parse.py
- [ ] test_util.py (util.py should already be done).
- [ ] setup.py

**Comment by josenavas** [comment]
I will take test_util.py (I do not haver permissions on this repo to modify your comment @ElDeveloper )

**Comment by ElDeveloper** [comment]
@josenavas, updated, thanks!

**Comment by josenavas** [comment]
working on setup.py

**Comment by josenavas** [comment]
And working on the remaining one... parse.py and test_parse.py

**Comment by mortonjt** [comment]
@wasade , I can take care of pep8ing `filter.py` and `test_filter.py`
