### ISSUE TITLE
Adding in more visualization options

### ISSUE THREAD

**Issue by mortonjt** [biocore/emperor#357]
There are a few features that I think would be really informative if added properly
- Shapes: https://github.com/biocore/emperor/issues/128
- Taxa colors: https://github.com/biocore/emperor/issues/61
- Point sizes: https://github.com/biocore/emperor/issues/337

There are the options that I see

<ol>
<li>Add 2-3 additional options to specify all of these attributes to every sample/taxa</li>
<li>Replace the `color-by` argument with a `sample-option` and `taxa-option` arguments to accept two tables of attributes (specifying color, shape, size, ...) for each</li>
<li>Couple these options with biom table (more distant future)</li>
</ol>

Option 2 may work out best since it could reduce the complexity of the command-line interface and shouldn't require too much infrastructure changes.

I would personally prefer Option 3, since it could mean less preprocessing and less complex CLI arguments for Emperor, but it would definitely infringe on backwards compatibility.

**Comment by ElDeveloper** [comment]
I don't know what you mean by taxa colors, but in the past we've been able to add taxonomy information to the mapping file (using `sumarize_taxa.py`) and color samples by the abundance of a particular taxa.

Point size is already supported by the visibility tab, unless I'm missing something.

**Comment by mortonjt** [comment]
Probably should have clarified that the taxa colors are only for the biplots

Right now, all of the taxa sphere and taxa vectors are colored white - see [drawTaxa`](https://github.com/biocore/emperor/blob/master/emperor/support_files/js/emperor.js#L1427)

I would really like to be able to create different colors for different taxa in the biplots.  For instance, I personally like to color taxa by phyla.

For point size, I was thinking about making each sample point a different size based on a metadata variable.  This could allow the viewer to visualize more metadata variables.

**Comment by ElDeveloper** [comment]
Got it, yeah I agree! This perhaps needs to be a new tab on the right.
And sorry, let me correct my previous comment, for the point size,
that's what the Scaling tab does.

**Comment by mortonjt** [comment]
Disregard my comment above about adding in two additional options.  I'm still in the process of understanding Emperor ...

Anyways, I think the coloring scheme for the metadata now provides a really awesome template.   I think we can use the same idea to specify shape and size for each point.

I would like to do the same thing for the taxonomies, addressing https://github.com/biocore/emperor/issues/75 and https://github.com/biocore/emperor/issues/61 in the near future.

**Comment by ElDeveloper** [comment]
Got it, makes a lot of sense! Shapes are tricky in 3D because of
perspective, but I think we can come up with something very compelling
if we put some thought into the shapes or the way these are rendered on
screen.  That being said, I think supporting interactive 2D plotting
would be nice and shapes there would make a huge difference, see #303.

**Comment by ElDeveloper** [comment]
This was largely addressed by #646
