### ISSUE TITLE
Modifying the biplots otu file parameter

### ISSUE THREAD

**Issue by mortonjt** [biocore/emperor#361]
Right now, emperor is taking in an otu table for the biplots.

Instead of inputting an otu table and doing the preprocessing in Emperor, I propose the following.
1. Push the biplot preprocessing procedure back into QIIME
2. Modify the -t parameter to take in a set of eigenvectors/eigenvalues for the OTUs instead of an OTU table.

This will not only make it easier to display compositional biplots, but will also make it significantly easier to display other biplots such a CA biplots.  Plus, it doesn't require major restructuring of the existing command line arguments.

**Comment by ElDeveloper** [comment]
I'm not sure I'm understanding this 100%, what are the specifics that
you would like to push back to QIIME?

**Comment by mortonjt** [comment]
I was referring to this [file](https://github.com/biocore/emperor/blob/master/emperor/qiime_backports/biplots.py)

The idea is the preprocessing would be to do the biplot calculations in QIIME.  QIIME will spit out a text file with the eigenvectors for the biplots.  This is not only to reduce preprocessing on Emperor, but it will make Emperor a bit more agnostic to what method is used to create the sample/feature ordinations.

Maybe I'm rambling.  I'd be happy to clarify these ideas over gchat.

**Comment by ElDeveloper** [comment]
Now I got it, thanks for the expanded explanation! I think it would be
more important to push this to scikit-bio though. What do you think?

**Comment by antgonza** [comment]
:+1: for moving to skbio.

**Comment by mortonjt** [comment]
I think that's a good idea!

We may want to discuss the file format.  Do we want to stick with the current text file format?  Or should we develop a new format.

Either way, might want to develop read/write IO methods for this.

**Comment by rob-knight** [comment]
Suggest quick call rather than 100 more emails? Thanks!


On Mar 9, 2015, at 3:14 PM, Yoshiki Vázquez Baeza <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm not sure I'm understanding this 100%, what are the specifics that
you would like to push back to QIIME?

**Comment by ElDeveloper** [comment]
This was fixed in #646: the Emperor object now obtains the data from the OrdinationResults container.
