### ISSUE TITLE
displayTaxaLabels is broken

### ISSUE THREAD

**Issue by antgonza** [biocore/emperor#368]
https://github.com/biocore/emperor/pull/359 broke JS when there are no taxa plots. See [this](http://emperor.colorado.edu/master/make_emperor/emperor_output/index.html)

**Comment by mortonjt** [comment]
Question - is this original master version, or the version that you are working with?

**Comment by antgonza** [comment]
Master. The issue is this line is called even if there is no taxa:
https://github.com/biocore/emperor/blob/master/emperor/support_files/js/emperor.js#L897

**Comment by antgonza** [comment]
Fixed #369
