### ISSUE TITLE
use emperor.microbio.me for RESOURCES_URL

### ISSUE THREAD

**Issue by antgonza** [biocore/emperor#382]
Currently emperor/core.py uses emperor.colorado but should be replaced to emperor.microbio.me once this is active

**Comment by ElDeveloper** [comment]
A problem with this is that we don't yet have emperor.microbio.me, or is this supposed to be in place?

**Comment by antgonza** [comment]
Not yet in place, thus an issue vs. asking to fix it in your PR.

**Comment by ElDeveloper** [comment]
Got it!
