### ISSUE TITLE
allow to change arrows colors in biplots

### ISSUE THREAD

**Issue by antgonza** [biocore/emperor#388]
Currently is always white ...

**Comment by ElDeveloper** [comment]
This can probably piggy-back on the color selector for the taxa
spheres. What do you guys think?

**Comment by antgonza** [comment]
AKA use same color for arrows and spheres? Fine with me.

**Comment by ElDeveloper** [comment]
Yes, exactly that.

**Comment by ElDeveloper** [comment]
This was fixed in #646: users can now select the metadata level to control visual attributes of the arrows..
