### ISSUE TITLE
The website emperor.colorado.edu is down

### ISSUE THREAD

**Issue by colinbrislawn** [biocore/emperor#408]
It looks like http://emperor.colorado.edu is currently offline.
http://www.isup.me/http://emperor.colorado.edu

:disappointed: 

Edit: I just realized that http://biocore.github.io/emperor/ is up and running fine. Is this the new website I should refer my collaborators to?

**Comment by josenavas** [comment]
That's correct @colinbrislawn

**Comment by josenavas** [comment]
sorry, actually it is emperor.microbio.me

**Comment by ElDeveloper** [comment]
Yes, emperor.colorado.edu is down and it will remain this way as we've
now transitioned fully to UCSD hardware. The new official website is:
http://emperor.microbio.me

@colinbrislawn, I've been trying to fix any remaining URLs pointing to
the old website, but I clearly have not succeeded, can you tell me where
did you find an occurrence of emperor.colorado.edu?
