### ISSUE TITLE
If a summarized taxa table has all zeros for a sample, emperor will silently fail

### ISSUE THREAD

**Issue by emperor-helper** [biocore/emperor#409]
If there's a summarized taxa table that gets passed and it has a column where all values are zeros, the code will execute just fine but when opening in the browser the following error will come up in the JavaScript console:

```
Uncaught TypeError: Cannot convert undefined or null to object
```

Reason is that all the biplot coordinates will end up being nan and that value/variable doesn't really exist in JavaScript. We should add a warning/check that validates for this.

**Comment by mortonjt** [comment]
:+1: Let's open up an issue for this

On Wed, Jul 15, 2015 at 10:37 AM, Penguin McHelper <notifications@github.com

**Comment by ElDeveloper** [comment]
This is no longer an issue since the decompositions are assumed to be computed outside emperor.
