### ISSUE TITLE
Handling multiple scenePlotViews

### ISSUE THREAD

**Issue by mortonjt** [biocore/emperor#414]
Right now there are a maximum number of 4 scenePlotViews (i.e. plots) that can be plotted at once in an upcoming PR for `biocore:new-api`.  The positions of these scenePlotViews are atm hard coded, and only the first scenePlotView can be colored.  This brings up the following question

1) How can different scenePlotViews be operated on (i.e. selected and colored)?
2) How can different scenePlotViews be positioned?
3) How can different scenePlotViews be opened and closed?

One option is to allow the user to open multiple windows, but this will require more careful thought.

**Comment by ElDeveloper** [comment]
@mortonjt, that makes sense though since this doesn't exist as part of
master (yet), would you mind adding a point/comment/task in #405? If
this is unresolved after #405 is merged then we should reopen this issue
then. If you agree, would you mind closing this issue?

**Comment by mortonjt** [comment]
Consider it closed.

The main reason why I wanted to open up this issue is so that we have a reminder when we are improving the code - I reference this particular issue in PR that I just launched against your `recolor` branch.

**Comment by ElDeveloper** [comment]
Thanks!
