### ISSUE TITLE
Biplot vectors can't be recolored

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/emperor#416]
There's no way to change the color of the vector lines when generating a biplot.

**Comment by mortonjt** [comment]
Do you think it would be more appropriate in Emperor 1.0, or should it be an immediate fix?

**Comment by ElDeveloper** [comment]
I think we should have an intermediate fix, since we probably want a
0.9.6 release with the project as is. Thoughts?

**Comment by mortonjt** [comment]
Ok.  Making that fix shouldn't be a big issue.
I'm thinking about recolor all of the vectors the same color as the taxa spheres?  Any objections?

**Comment by ElDeveloper** [comment]
I think that's a reasonable choice. @antgonza or others, do you think that's good enough or should we have a separate controller for the vectors color ... which might make sense.

**Comment by antgonza** [comment]
I think it will be better to have a different selector ...

**Comment by ElDeveloper** [comment]
@mortonjt, any updates on this?

**Comment by mortonjt** [comment]
No updates atm.  Planning on addressing this once the new-api gets merged.

**Comment by ElDeveloper** [comment]
Since we want to do a 0.9.6 release that will not have new-api merged in
it, we will need to have this in, maybe we can chat IRL.

**Comment by ElDeveloper** [comment]
This was fixed in #646. The colors tab allows for changing the color of the arrows.
