### ISSUE TITLE
evaluate dat.gui for menus

### ISSUE THREAD

**Issue by antgonza** [biocore/emperor#418]
@iprotsyuk is using dat.gui for menus, should be good to evaluate for next Emperor version

**Comment by ElDeveloper** [comment]
Looks very cool, here's a link in case someone is wondering:

http://workshop.chromeexperiments.com/examples/gui/#1--Basic-Usage

**Comment by iprotsyuk** [comment]
I'd add that this library doesn't have much room for customization. Therefore, I recommend you to check whether it contains all the widgets/controls needed for Emperor. Otherwise, it might not be not easy to adapt it for your needs.

**Comment by ElDeveloper** [comment]
We've had this discussion in our weekly meetings and we won't use dat.gui.
