### ISSUE TITLE
Allow for merging of metadata columns

### ISSUE THREAD

**Issue by clozupone** [biocore/emperor#419]
It would be nice if one could merge 2 different metadata columns into one new column within emperor. For instance if you had one column for ethnicity and one for disease status, it would create a new column containing ethnicity+disease status.

**Comment by antgonza** [comment]
You bit me before I could reply to the other thread. This is a duplicate https://github.com/biocore/emperor/issues/160

**Comment by clozupone** [comment]
Antonio, you have always been so kind and helpful to me - I would never bite you :-)


On Aug 26, 2015, at 11:33 AM, Antonio Gonzalez <notifications@github.com<mailto:notifications@github.com>>
 wrote:


You bit me before I could reply to the other thread. This is a duplicate #160<https://github.com/biocore/emperor/issues/160>

**Comment by ElDeveloper** [comment]
Closing this in favor of #160, hopefully we will be able to address this as part of #405
