### ISSUE TITLE
Clicking on index.html file leads to WebGL error

### ISSUE THREAD

**Issue by davis164** [biocore/emperor#422]
Hi,

I have a variety of PCoA plots as part of my QIIME output. However, if I right click the index.html files and tell them to open with Chrome, I get an error saying that Web GL is disabled. However, Web GL is in fact enabled. I cannot see the plots. Also, if I do a webgl check at https://get.webgl.org/, it tells me that Web GL is supported. What could be the problem and how can I get my index.html files from QIIME to show up?

Thanks!

**Comment by antgonza** [comment]
Which version of emperor are you using?

**Comment by davis164** [comment]
How do I find that out? Do I need to install it on my own before I can view my QIIME files?

Ariangela J. Kozik 
Ph.D Student 
Interdisciplinary Life Science 
Purdue University 

----- Original Message -----

**Comment by antgonza** [comment]
Emperor gets installed with QIIME. You can check the version by running: make_emperor.py --version

**Comment by davis164** [comment]
Sorry for the delay. The version is 0.9.51

Ariangela J. Kozik 
Ph.D Student 
Interdisciplinary Life Science 
Purdue University 

----- Original Message -----

**Comment by antgonza** [comment]
Strange. That's the latests version of Emperor and should be fine. However, other option is that you generated those plots with an older version. Could you do `head index.html` on your file? There you should find the version of Emperor used to generate that plot. If it's the latest could you share your files so we can take a look?

**Comment by davis164** [comment]
Yes it is listed as the latest version. Attached is my index.html file for a weighted unifrac plot. 
Let me know if you need anything else

Thanks!

Ariangela J. Kozik 
Ph.D Student 
Interdisciplinary Life Science 
Purdue University 

----- Original Message -----

**Comment by antgonza** [comment]
You can't attach files to github, either send me an email or add it to dropbox and send us the link. It will be better if you send us the full folder. Thanks.

**Comment by davis164** [comment]
what is the email address I can send to?

Ariangela J. Kozik 
Ph.D Student 
Interdisciplinary Life Science 
Purdue University 

----- Original Message -----

**Comment by antgonza** [comment]
antgonza@gmail.com

**Comment by davis164** [comment]
I cannot upload the whole folder. How can I dropbox it to you?

Ariangela J. Kozik 
Ph.D Student 
Interdisciplinary Life Science 
Purdue University 

----- Original Message -----

**Comment by antgonza** [comment]
Yup.

**Comment by davis164** [comment]
I'm sorry, I wasn't clear. I know I can dropbox it, but I don't know how as I am not very familiar with Dropbox. Is there a link somewhere that will get it directly to you?

Ariangela J. Kozik 
Ph.D Student 
Interdisciplinary Life Science 
Purdue University 

----- Original Message -----

**Comment by antgonza** [comment]
Right click on the zipped file and you should have an option to share the dropbox link, this will copy it, then you can paste it.

**Comment by davis164** [comment]
https://www.dropbox.com/sh/oo4z39e0fe69v1t/AAC1sjWJthOoJi8cTD1Sumwsa?dl=0


Ariangela J. Kozik 
Ph.D Student 
Interdisciplinary Life Science 
Purdue University 

----- Original Message -----

**Comment by antgonza** [comment]
I can open that file without issues in Chrome, could you check that you have the latests version of Chrome? Version 45.0.2454.85 (64-bit)

**Comment by davis164** [comment]
how do I do that?


Ariangela J. Kozik 
Ph.D Student 
Interdisciplinary Life Science 
Purdue University 

----- Original Message -----

**Comment by antgonza** [comment]
https://support.google.com/chrome/answer/95414?hl=en

**Comment by davis164** [comment]
Chrome Version 45.0.2454.85 m

Ariangela J. Kozik 
Ph.D Student 
Interdisciplinary Life Science 
Purdue University 

----- Original Message -----

**Comment by antgonza** [comment]
Can you see the plots now? If not, could you tell us the OS, make and model of your machine ... it's weird cause it actually opens for me.

**Comment by davis164** [comment]
nope still nothing. Dell Optiplex 7010 running Windows 7 Enterprise 64 bit operating system Intel(R) Core i7-3770 CPU @ 3.40GHz

Ariangela J. Kozik 
Ph.D Student 
Interdisciplinary Life Science 
Purdue University 

----- Original Message -----

**Comment by antgonza** [comment]
Sorry for the slow reply. It's hard to debug without a Windows machine. Anyway, the issue is that the newest official Windows Chrome doesn't behave as expected. However, https://www.google.com/chrome/browser/canary.html does.

**Comment by meiruv** [comment]
Hi there
I've been having the same issue, I'm using the same version of qiime and emperor as davis164 does and can't install the canary chrome because I'm working on linux.
do you have any idea for me too?
thanks in advance, Meirav :)

**Comment by ElDeveloper** [comment]
@meiruv, can you access the plots shown here:

http://emperor.microbio.me/master/make_emperor/biplot/index.html
http://emperor.microbio.me/master/make_emperor/jackknifed_pcoa/index.html
http://emperor.microbio.me/master/make_emperor/vectors/index.html

**Comment by meiruv** [comment]
sorry for the late reply , I haven't been to work until today.

I can access your plots.

**Comment by ElDeveloper** [comment]
If you can access and view those plots, then the problem might be either: (1) you haven't yet extracted the full list of files into your computer i.e. all the contents of emperor_required_resources and index.html or (2) you are trying to open index.html without the `emperor_required_resources` folder.

**Comment by meiruv** [comment]
indeed I lacked the emperor_required_resources, now it works.

thank you very much!

**Comment by ElDeveloper** [comment]
Great, thanks for confirming this!
