### ISSUE TITLE
can't open emperor plots from my computer

### ISSUE THREAD

**Issue by meiruv** [biocore/emperor#425]
Hi there

I've been working on microbiome for a while now and whenever I try to open an emperor plot from my computer I can't for some reason.
I work on an HP-elitebook, did all the settings I was supposed to (according to your land page instructions) and still the plots won't open.

any help?

thanks in advance- Meirav :)

**Comment by antgonza** [comment]
Have you taken a look to https://github.com/biocore/emperor/issues/422?
