### ISSUE TITLE
I am receiving this error when I try to test for a correct installation!

### ISSUE THREAD

**Issue by ElhamKarimi** [biocore/emperor#430]
I am receiving this error when I try to test for a correct installation! what should I do?!
File "/Users/elhamkarimi/anaconda/bin/make_emperor.py", line 415
    except ValueError, e:
                     ^
SyntaxError: invalid syntax

Thanks! I am really naive in this area .. sorry if my question is so basic

**Comment by antgonza** [comment]
Can you post your full command and traceback?

**Comment by ElhamKarimi** [comment]
Sorry you mean this : Elhams-MacBook-Air:~ elhamkarimi$ make_emperor.py
  File "/Users/elhamkarimi/anaconda/bin/make_emperor.py", line 415
    except ValueError, e:
                     ^
SyntaxError: invalid syntax

**Comment by ElhamKarimi** [comment]
I just open a new widow and try to verify my installation

**Comment by ElDeveloper** [comment]
Hmmmm, is this by any chance python 3? Can you try running the following
command: python --version  Emperor is only supported in python 2.7.x, we
are moving to support 3.x sometime soon but not yet.

**Comment by ElDeveloper** [comment]
I'm closing as we haven't heard back from the user, feel free to reopen if appropriate though.
