### ISSUE TITLE
Color numeric metadata by gradient (instead of by category)

### ISSUE THREAD

**Issue by cuttlefishh** [biocore/emperor#440]
For numeric values -- e.g. age, pH, latitude -- when there are more than 5 or so values (categories), it's very difficult to see if there's a trend. What's needed is a checkbox or something that changes from categorical coloring to colormap (gradient) coloring.

This is something I've brought up before. At the Qiime workshop in Costa Rica, where we had students give presentations on a variety of EMP studies in Qiita, which they analyzed in Qiime, they were also looking for an ability to color by gradient. Thanks!

**Comment by ElDeveloper** [comment]
Noted as part of #405, thanks!

**Comment by squirrelo** [comment]
Added in #456

**Comment by ElDeveloper** [comment]
@squirrelo, let's leave this open until `new-api` is part of `master` (your commit message should already take care of that). I'll add a new label `fixed in new-api` to avoid confusion.

**Comment by cuttlefishh** [comment]
:boom:
