### ISSUE TITLE
Question about Emperor

### ISSUE THREAD

**Issue by cevans58** [biocore/emperor#443]
will Emperor install and run on a PC rather than a Mac-based system? Can I load and run the necessary support software as well?  Thanks you. Chris
 
Christian C. Evans, PT, PhD
Professor, Physical Therapy
Midwestern University
555 31st Street, AH 340E
Downers Grove, IL 60515
(630) 515-7249

**Comment by ElDeveloper** [comment]
@cevans58 yes, emperor should be able to work. The script interface that generates the plots only depends on [scikit-bio](http://scikit-bio.org) and qcli. The plots themselves can run in any browser that supports WebGL. Let us know if you have any trouble!

**Comment by cevans58** [comment]
Thank you!  Best, Chris

**Comment by ElDeveloper** [comment]
@cevans58 no problem, I'll close this issue for now, but feel free to re-open.

**Comment by cevans58** [comment]
I am having trouble installing this on my PC.  I tried to install scikit-bio using Anaconda but I couldn’t get it to install.  Based on what I’ve read online, official support for Windows is scheduled for July 2016 . Do the developers you are working with have any documentation on how they installed it on a windows machine? Thank you.  Chris

**Comment by ElDeveloper** [comment]
@cevans58, I'm so sorry, I just realized I misread your original question, let me correct my answer, no Emperor is not intended to run on Windows, you may be able to get it to work, but we don't really support it; the web interface however should work on whatever platform. I'm terribly sorry for the confusion.

**Comment by cevans58** [comment]
Yoshiki:  Thank you for the response.  Can you tell me if there are directions as to how to use the web interface?  I didn’t see anything on the Emperor web page.  Chris

Christian C. Evans, PT, PhD
Professor, Physical Therapy
Midwestern University
555 31st Street, AH 340E
Downers Grove, IL 60515
(630) 515-7249

**Comment by ElDeveloper** [comment]
Hello Chris, by web interface I mean the one of generated plots. A
tutorial on how to use the interface can be found here:
http://biocore.github.io/emperor/tutorial_index.html
