### ISSUE TITLE
Dynamically upload new metadata and update plot

### ISSUE THREAD

**Issue by jwdebelius** [biocore/emperor#445]
In a meeting with Rob this morning, he thought it would be awesome if, rather than regenerating an emperor plot every time the mapping file was updated, it was instead possible to update the information on-the-fly using a tsv with a new metadata or updated metadata column. (Rather than the current solution of regenerating the full plot).

This would more easily facilitate exploration of data during collaborative meetings, where the collaborator may have forgotten a key piece of metadata or an obvious mislabeling comes up.

**Comment by mortonjt** [comment]
Right now, we are developing an IPython compatible API to allow quick and
easy updates.  Does this answer your concern?

**Comment by jwdebelius** [comment]
Yep, I think the Jupyter API solves this issue. Thanks for awesome work on that!

**Comment by ElDeveloper** [comment]
Thanks for closing @jwdebelius 👍
