### ISSUE TITLE
Axis labels disappear

### ISSUE THREAD

**Issue by st01565** [biocore/emperor#449]
Hi,
When I export my PCoA plot (on a Mac) as SVG the axis labels seems to disappear. Is there a quick fix to this issue, or do I just add them in GIMP or Illustrator? 

Thanks,

Rune

**Comment by ElDeveloper** [comment]
Dear Rune, we currently don't have a way to write the axes labels to the SVG file, but we are working on this as part of #405, and we already have a an issue for this in #87 (I'll close this issue but feel free to re-open it). As for a quick fix, fixing in GIMP or Illustrator is what I personally do and probably the easiest.
