### ISSUE TITLE
interpretation about the plot axis

### ISSUE THREAD

**Issue by capricy** [biocore/emperor#453]
Hello, there,

I just learned to run qiime analysis and got emperor plot for the beta diversity results. My question is what those PC percentages along the axes mean?  

Thank you very much for any inputs!

Cyan

**Comment by ElDeveloper** [comment]
Each of these numbers refer to the percentage of variation explained by each axis of the ordination.

Although [this link](http://ordination.okstate.edu/overview.htm) refers to PCA, the same applies to PCoA:

> The eigenvalues represent the variance extracted by each axis, and are often conveniently expressed as a percentage of the sum of all eigenvalues (i.e. total variance).
