### ISSUE TITLE
connecting the samples with a metadata category

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [biocore/emperor#540]
we're often doing longitudinal studies and are plotting samples from multiple time points on the same PCOA plot.  it might be convenient to connect those samples, from the same animal (defined by the metadata), with a line that indicates position over time.  very much like the animations, but in a static sense.

**Comment by antgonza** [comment]
You can do that via:
```
  --add_vectors=ADD_VECTORS
                        Comma-sparated category(ies) used to add connecting
                        lines (vectors) between samples. The first category
                        specifies the samples that will be connected by the
                        vectors, whilst the second category (optionally)
                        determines the order in which the samples will be
                        connected. [default: [None, None]]
```

Example: http://emperor.microbio.me/master/make_emperor/vectors/index.html

**Comment by antgonza** [comment]
@ConstantinoSchillebeeckx if this works for you, could you close this issue?

**Comment by ConstantinoSchillebeeckx** [comment]
It looks like this "bakes" the lines into the visualization, ideally they'd be dynamically adjustable but, yes, this does resolve the issue.  Thanks!

**Comment by antgonza** [comment]
What do you mean with dynamically adjustable? Which characteristics will you like to change?

**Comment by ConstantinoSchillebeeckx** [comment]
- adjust the coloring of each connecting line based on metadata
- hiding/showing individual connecting lines

**Comment by antgonza** [comment]
Got it, have you check the menus? For example:
- Color by metadata
![color-by-metadata](https://cloud.githubusercontent.com/assets/2014559/19119049/bde11566-8adb-11e6-9510-b006e6891a40.gif)
- Show/Hide
![show-hide](https://cloud.githubusercontent.com/assets/2014559/19119060/c9ad7060-8adb-11e6-8556-9ae55f16d1a4.gif)

**Comment by ConstantinoSchillebeeckx** [comment]
I just got schooled! Thanks!
