### ISSUE TITLE
method for embedding 3d interactive image

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [biocore/emperor#551]
I use a lot of HTML/CSS to document my results/studies and find that I'm often using screenshots of a particular PCOA plot to communicate results.  It might be nice for there to be a method by which a particular formatting of the PCOA plot (colors, scaling, visibility, etc) could be "baked-in" and saved as a stand alone interactive figure (without the emperor interface).  This figure could then be displayed in documentation (perhaps through an `iframe`) instead of the flat screen shot.

Some reference ideas/implementations could might be:
- [github viewer of STL files](https://github.com/blog/1465-stl-file-viewing)
- [3D pdf](http://www.3dpdfconsortium.org/)

**Comment by ElDeveloper** [comment]
Hello @ConstantinoSchillebeeckx, I think we have a "partial" solution to what you describe, let us know what you think. With [version 1.0](http://emperor.microbio.me/uno/) of emperor, you can embed the plots in Jupyter notebooks (for example see [this notebook](http://nbviewer.jupyter.org/github/biocore/emperor/blob/new-api/examples/keyboard.ipynb)), and to save settings (coloring, visibility, etc) you can shift + right click in a plot and produce a JSON file with the settings that store all this information.

The [Python API](http://emperor.microbio.me/uno/build/html/index.html) provides an option to generate plots that can be embedded as a DIV in any website. All you have to do is use `remote=True`.

Would something like this work, or do you have something else in mind?

**Comment by ConstantinoSchillebeeckx** [comment]
Thanks for the response Yoshi - v1 is really starting to come together!  

Indeed, your suggestion isn't quite what I'm hoping for. Is there a way to directly load the saved JSON file and display only it without the right-hand GUI?

I'm thinking about this with regards to my exploratory data analysis and eventual use as documentation.  When I share the analysis, I would want the notebook to load with the PCOA plot already formatted as I intended without the potential distraction of the GUI.

**Comment by ElDeveloper** [comment]
I understand now! You are right, this is currently not possible, but it is something that we definitely would want as part of the Python and JavaScript API, thanks for the suggestion!

Like you mention, the way we need to do this, is by programmatically loading the settings file, which would imply a change in the `EmperorController` JavaScript object, as well as a change to the Python object, such that you can select what are the predefined settings that a plot loads with.

**Comment by ElDeveloper** [comment]
@ConstantinoSchillebeeckx I believe this is now addressed by #579.
