### ISSUE TITLE
emperor examples issue

### ISSUE THREAD

**Issue by kerimlcr** [biocore/emperor#560]
Hi
i try https://github.com/biocore/emperor/blob/new-api/examples/keyboard.ipynb examples but 
>import pandas as pd, numpy as np
>from emperor import Emperor, nbinstall
---
ImportError                               Traceback (most recent call last)
<ipython-input-2-22e4b2fe55e7> in <module>()
----> 1 from emperor import Emperor, nbinstall

/usr/lib/python2.7/dist-packages/emperor/__init__.py in <module>()
      8 __version__ = "0.9.60"  # noqa
      9 
---> 10 from emperor.core import Emperor
     11 
     12 __all__ = ['Emperor', 'biplots', 'format', 'filter', 'parse', 'sort', 'util']

/usr/lib/python2.7/dist-packages/emperor/core.py in <module>()
     24 from __future__ import division
     25 
---> 26 from emperor.format import (format_mapping_file_to_js, format_pcoa_to_js,
     27                             format_taxa_to_js, format_vectors_to_js,
     28                             format_comparison_bars_to_js,

/usr/lib/python2.7/dist-packages/emperor/format.py in <module>()
     18 import numpy as np
     19 
---> 20 from emperor.util import (keep_columns_from_mapping_file,
     21                           get_emperor_library_version)
     22 from emperor._format_strings import (_ELLIPSE_OPACITY_SLIDER,

/usr/lib/python2.7/dist-packages/emperor/util.py in <module>()
     21                                                    scale_custom_coords)
     22 from emperor.qiime_backports.parse import mapping_file_to_dict
---> 23 from emperor.qiime_backports.util import (MetadataMap, is_valid_git_refname,
     24                                           is_valid_git_sha1, summarize_pcoas)
     25 

/usr/lib/python2.7/dist-packages/emperor/qiime_backports/util.py in <module>()
     10 __status__ = "Development"
     11 
---> 12 from skbio.stats.spatial import procrustes
     13 from emperor.qiime_backports.parse import parse_mapping_file_to_dict
     14 

ImportError: No module named spatial
---
all Dependencies is installed
i try latest version(0.9.60 stable version)
What could be the problem ?
regards

**Comment by ElDeveloper** [comment]
@kerimlcr, it looks like your system is using 0.96.0, those examples are created with the 1.0.x beta release. To install a compatible version, see the **Pre-releases section** on the installation [instructions here](https://github.com/biocore/emperor/blob/new-api/INSTALL.md#emperor-installation-notes), and for more information see [this link](http://emperor.microbio.me/uno/). Note that version 1.0.x is a re-implementation of Emperor, most importantly, we provide a Python-level API (as noted in the notebooks), and the project now relies on QIIME2 to access the command line interface.
