### ISSUE TITLE
toggling the visibility of samples based on metadata requires a few extra clicks

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/emperor#564]
In 1.0.0beta5, the checkboxes in the *Visibility* tab don't work as expected. After unclicking a box, you have to click on the text to the right of that box to get the samples to disappear in the plot.

**Comment by ElDeveloper** [comment]
This was fixed in https://github.com/biocore/emperor/pull/558, however we have not yet made a new release, this problem is solved in the development version.
