### ISSUE TITLE
No visualization of PCoA, parallel working

### ISSUE THREAD

**Issue by ealatham** [biocore/emperor#567]
Greetings, I am unable to view the PCoA (screenshots). I'm not sure if this is a bug or a biproduct of my dataset. Thanks a lot!
[
![screen shot 2017-03-23 at 4 35 53 pm](https://cloud.githubusercontent.com/assets/26636728/24271360/e55bc84e-0fe6-11e7-9de5-0fb564826bcd.png)
](url)
[
![screen shot 2017-03-23 at 4 37 04 pm](https://cloud.githubusercontent.com/assets/26636728/24271386/fa421be6-0fe6-11e7-890d-4a962d5a96ae.png)
](url)
![screen shot 2017-03-23 at 4 38 23 pm](https://cloud.githubusercontent.com/assets/26636728/24271434/28aa93be-0fe7-11e7-94b0-841611c087e4.png)

**Comment by ElDeveloper** [comment]
What version of Emperor are you using? You can check this by running `make_emperor.py --version` or by copying and pasting the output of `head weighted_unifrac_emperor_pcoa_plot/index.html` (assuming you are using a UNIX-like system).

Can you visualize the plot in this link:
http://emperor.microbio.me/master/make_emperor/biplot/index.html

**Comment by ealatham** [comment]
Hi there,
Emperor Version: 0.9.51
I cannot visualize that plot. 
Thanks!

**Comment by ElDeveloper** [comment]
Then it seems like the problem might be related to the hardware where you are running this. Can you try this website: https://get.webgl.org You should see a rotating cube.

**Comment by ealatham** [comment]
I do it a rotating cube. I tried opening in firefox and works perfect, thanks a lot.

**Comment by ElDeveloper** [comment]
Great, thanks for posting an update 👍
