### ISSUE TITLE
Set custom "null" value for continous data

### ISSUE THREAD

**Issue by jwdebelius** [biocore/emperor#585]
It would be really helpful if we could designate an unknown value for continous data. For example, in the global gut, I colored the gradient by age, and designated my missing values as red. 

![global gut](https://cloud.githubusercontent.com/assets/5534846/25775676/47154dac-3270-11e7-8409-a37881f809bc.png)

The goal would be to display the missing values with a certain color scheme, while casting the rest to a gradient. The current implementation requires replacing those values with a number (i.e. -3), and then adjusting the colormap for that number. 

...That said, this may be a problem that can be solved at another level, like maybe specifying in something like break_4w and then having the hand off that way.

**Comment by ElDeveloper** [comment]
If you are using the newest version of Emperor this is possible when you select a continuous color map, and click on the checkbox that reads "Continuous values", this will map all the numeric values to the scheme, and non-numeric values to gray, but you can change this. For an example see this animated gif:

![missing-data](https://cloud.githubusercontent.com/assets/375307/25786978/e8938e50-3351-11e7-9fc4-f03845d12946.gif)

The step to notice are the selection of a continuous colormap, clicking on the checkbox, and then selecting the color for the missing data.

**Comment by jwdebelius** [comment]
This is brilliant. I may have some other problem with my data.
Thank you for already reading my mine.

**Comment by ElDeveloper** [comment]
🎉 🔮
