### ISSUE TITLE
Allow filtering of taxa strings for biplots

### ISSUE THREAD

**Issue by walterst** [biocore/emperor#59]
The full taxa strings can be cumbersome to visualize.

An example taxonomy string:
k__Bacteria;p__Firmicutes;c__Clostridia;o__Clostridiales;f__Ruminococcaceae;g__Ruminococcus;s__

The most informative (and least abusive of real estate) could have just g__Ruminococcus.

It might be helpful to allow the entire taxa string to be displayed, or one or more of the semicolon separated levels (so allow phylum and genus level to be displayed) as a column selected of the taxa.

Could also be handy to allow modification of the text (so only display genus level  g__Ruminococcus) and then delete the prefix, so it just shows Ruminococcus.

**Comment by mortonjt** [comment]
I think I start looking into this problem

**Comment by ElDeveloper** [comment]
AWESOME!! Thanks!!!

**Comment by ElDeveloper** [comment]
This was fixed in #359
