### ISSUE TITLE
Spheres, but not animations rotate

### ISSUE THREAD

**Issue by jwdebelius** [biocore/emperor#593]
I tried to rotate the axes, and the spheres relocate as expected. However, the animation trajectory is independent of the axes. So, you can't rotate while animating or rotation with animation.

![screen shot 2017-06-22 at 9 12 45 am 2](https://user-images.githubusercontent.com/5534846/27444461-4e62a73c-572b-11e7-856d-9759a53b8afe.png)

**Comment by ElDeveloper** [comment]
Does this happen when you change the visible axes? Or re-orient an axis?

**Comment by jwdebelius** [comment]
I think I'd reoriented and flipped the axes.

**Comment by ElDeveloper** [comment]
Noted, yes that makes sense, the trajectories displayed for animations
are computed only once (when the user hits play), the only workaround
right now would be to re-orient axes as needed and then click play.
