### ISSUE TITLE
Number of samples

### ISSUE THREAD

**Issue by sjanssen2** [biocore/emperor#594]
I am missing the information about the number of samples in the plot for the new Emperor. It used to be in the top left corner. Is there a different place where to find it (other than going back to the input files)?

**Comment by antgonza** [comment]
I _really_ miss this ... can we re-add?

**Comment by ElDeveloper** [comment]
Yes we can! Would the same tab on the top left be enough? "XXX/YYY 
Points".

**Comment by antgonza** [comment]
for me, yes!

**Comment by sjanssen2** [comment]
I would love it!

**Comment by wasade** [comment]
👍 ✖️ 💯
