### ISSUE TITLE
Plots won't open in macOS Safari 11/11.1: "SecurityError: The operation is insecure".

### ISSUE THREAD

**Issue by kliere** [biocore/emperor#610]
Hi, 

Qiime generated plots won't open any more with the new macOS Safari 11/STP11.1 apps. The error is: "SecurityError: The operation is insecure". With Safari 10 the plots work as expected.

Emperor Version: 0.9.51
macOS 10.12.6 (16G29), Safari 11 (12604.1.38.1.7)
macOS 10.13 Beta (17A362a), Safari TP 11.1 (13605.1.6.0.1)

Cheers,

Karsten

**Comment by ElDeveloper** [comment]
@kliere, thanks for reporting this. I tried an [example plot](http://emperor.microbio.me/master/make_emperor/biplot/index.html) in Safari 11 running under macOS 10.12.6 version (I don't have access to 10.13). Where is this message shown? Is it printed on the JavaScript console or shown as an alert window?

Can you access this site: https://get.webgl.org

**Comment by kliere** [comment]
@ElDeveloper, thank you for looking into this. Well, online examples work just fine, as does the test for WebGL on https://get.webgl.org both on Safari 11 and 11.1 / macOS 10.12/10.13. However, the Emperor files generated with Qiime opened as file:/// do not work (they, however, work in Firefox and Chrome). 
![screen shot 2017-09-21 at 20 35 41](https://user-images.githubusercontent.com/11179544/30712490-7b6194cc-9f0c-11e7-92aa-576f26008310.png)
The message is visible in the web inspector console of Safari.

Cheers,

Karsten

**Comment by ElDeveloper** [comment]
Got it, can you see if you can view the plot if you move the folder to a Volume that's local, for example just placing the folder in the /Users/you/Desktop?

**Comment by kliere** [comment]
That, unfortunately, makes no difference. Neither when placed on the Desktop, nor within the Home folder:
![screen shot 2017-09-22 at 09 04 28](https://user-images.githubusercontent.com/11179544/30733000-59e572b4-9f75-11e7-832d-d6cba08507df.png)

**Comment by ElDeveloper** [comment]
@kliere, thanks for checking that, can you try installing emperor version 0.9.60, with pip it would be:

```
pip install emperor==0.9.60
```

**Comment by kliere** [comment]
No, unfortunately, emperor version 0.9.60 makes no difference. 

I guess it is somehow relayed to one of the security patches in the latest webkit version. All webkit-based browsers I've tested so far, show the very same error. Only Chrome (with its on webkit fork), iCab and Firefox (with their on rendering engines) so far display Emperor content just fine.

**Comment by ElDeveloper** [comment]
@kliere, thanks for following up, I am able to reproduce this error in Safari, and with the old versions of Emperor. The new version however does not present this problem.

**Comment by ElDeveloper** [comment]
Forgot to mention, the new version of emperor (one that doesn't present this problem in Safari) is only available for Python 3, and the command line interface is only available through QIIME 2.

Thanks for reporting this!

**Comment by Lyle101** [comment]
Set "Disable local file restrictions" in the Develop menu.
see:  [Safari 11 gets SecurityError (DOM exception 18) when accessing localStorage](https://forums.developer.apple.com/thread/87778)
