### ISSUE TITLE
Emperor plots on windows chrome

### ISSUE THREAD

**Issue by nagpal511** [biocore/emperor#616]
Hi,
I just had a miseq run which i analyzed by Qiime preprocessing and Qiime visualtinl apps. However, I am not able to view the (beta-diversity) PCoA plots from the index.html link. Every time I click on this link, it shows a big "Emperor' logo for a second and then leaves a blank screen. All other plots i.e. alpha-diversity (rarefaction) plots and taxa summary bar and area charts are opened without any problem. Could you please suggest a solution for this problem? I am using a windows HP desktop with Google chrome.

Many thanks!
Ravi

**Comment by ElDeveloper** [comment]
Can you confirm that you can see a rotating cube when you access this URL:
https://get.webgl.org

**Comment by nagpal511** [comment]
Yes I can see the rotating cube.

**Comment by ElDeveloper** [comment]
Could you open the JavaScript console? View > Developer > JavaScript Console. Maybe there's an error message not being caught. If there are any errors, please send a screenshot or copy/paste the error here. 👍

**Comment by nagpal511** [comment]
Sure. But could please guide me on how to open that console? I am not familiar with java.

**Comment by ElDeveloper** [comment]
This [StackOverflow answer](https://stackoverflow.com/a/66434/379593) indicates that you can do this by using <kbd>CTRL</kbd>-<kbd>SHIFT</kbd>-<kbd>J</kbd>.

**Comment by nagpal511** [comment]
![capture1](https://user-images.githubusercontent.com/33159970/32116890-5c764a4c-bb1a-11e7-8115-0500245a8349.PNG)

**Comment by nagpal511** [comment]
I did "Ctrl-shift-J" on a new chrome tab and this popped out.

**Comment by nagpal511** [comment]
And when I pressed 'F12' I got this:

![capture2](https://user-images.githubusercontent.com/33159970/32116986-b96f8e7a-bb1a-11e7-8933-2519e750aa08.PNG)

**Comment by ElDeveloper** [comment]
Did you do this while you had the Emperor file open? As a side note, can you open and view the plot in this URL:
http://emperor.microbio.me/master/make_emperor/biplot/index.html

**Comment by nagpal511** [comment]
Yes I can open and view these plots!

And when I ran 'CTRL-SHIFT-J' with Emperor file being opened, this is what I got:
![capture3](https://user-images.githubusercontent.com/33159970/32117361-07a36606-bb1c-11e7-9b97-2d69c4febf31.PNG)

**Comment by nagpal511** [comment]
This is strange. I can view your plots but not mine.

**Comment by ElDeveloper** [comment]
It seems like the visualization you generated with BaseSpace is missing some resources, namely jQuery. Would you mind zipping your emperor visualization and uploading it here?

**Comment by nagpal511** [comment]
[QIIME_Visualizations_10.zip](https://github.com/biocore/emperor/files/1423455/QIIME_Visualizations_10.zip)

**Comment by nagpal511** [comment]
Thanks again, for your valuable time & help. Here is the complete folder I got after downloading the analysis.

**Comment by nagpal511** [comment]
Hi Yoshiki, could you find time to resolve the issue?

**Comment by ElDeveloper** [comment]
I just had a look, it seems like the outputs produced by the BaseSpace app are incomplete i.e. they are missing some resource files required for Emperor to work.

This does not appear to be a problem with QIIME or the QIIME app, this seems to be a problem with BaseSpace itself not copying some files.

I've uploaded both plots (unweighted and weighted) with all the required resources:

[Archive.zip](https://github.com/biocore/emperor/files/1427972/Archive.zip)

**Comment by nagpal511** [comment]
Thank you very much, Yoshiki. But I still cannot view the plots, eve after disabling WebGL and enabling "Override software rendering list" on my chrome.

**Comment by ElDeveloper** [comment]
Can you send us a screenshot of the message you are seeing? I tested both plots in Chrome and they work for me.

**Comment by nagpal511** [comment]
![capture4](https://user-images.githubusercontent.com/33159970/32185721-71b8820e-bd76-11e7-9dfb-6e1163d571e5.PNG)

**Comment by nagpal511** [comment]
I am getting this only, even after I enable or disable WebGL.

**Comment by ElDeveloper** [comment]
I think you need to extract the contents of the zip file, you might be viewing the index.html file from within the "unzipping" software in Windows.

**Comment by nagpal511** [comment]
Thank you very much, Yoshiki. I can now view the plots. Greatly appreciated!!!
By the way, what would be your suggestion or what should I do now to ensure that I don't face the same problem during my next miseq runs?

**Comment by ElDeveloper** [comment]
I believe this is a problem with the BaseSpace downloader, so my recommendation would be to reach out to the Illumina team and ask them why were some files not downloaded.

**Comment by nagpal511** [comment]
Ok Yoshiki, I will do that now. By the way, is it possible for me to perform Qiime analysis on my windows PC? I mean I don't have Linux or Mac, just a routine office PC with latest version of MS Windows. 
If so, then I won't have to use base space and I would have more control over more options and parameters.

**Comment by ElDeveloper** [comment]
You can run QIIME analyses in Windows if you use a virtual machine:
http://qiime.org/install/virtual_box.html

**Comment by nagpal511** [comment]
Alright, Yoshiki, will give it a try. Thanks!!!
PS. Does your name 'Yoshiki' come from Japan?

**Comment by ElDeveloper** [comment]
Yes it is a Japanese name 🗾 👍

**Comment by nagpal511** [comment]
I see. I simply asked because I've worked in Japan for 5 years and that was the best time of my life. Just loved everything about Japan :)

**Comment by nagpal511** [comment]
Hi Yoshiki, sorry to poke you again but I had a little query if you could advice. We're running 16S miseq sequencing as per the earth microbiome project protocol (515F and 806R primers; V4 region) and analyzing the data using qiime preprocessing and qiime visualization apps on base space. But we only get output up to genus level. Is there anyway to get data up to species level?
Thanks very much in advance!

**Comment by nagpal511** [comment]
Hi Yoshiki, I'm having some trouble with qiime preprocessing base space app. Could you please be kind enough to be able to help?
