### ISSUE TITLE
Problem installing emperor

### ISSUE THREAD

**Issue by ehossain1982** [biocore/emperor#657]
Emperor plot will not open in safari. I have latest python, and anaconda navigator. tried to install emperor. got this error:

pip install emperor
Collecting emperor
  Using cached emperor-0.9.60.tar.gz
    Complete output from command python setup.py egg_info:
    error in emperor setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Unordered types are not allowed
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/jt/hk4hzw2n4t56kzt_92xcj06c0000gn/T/pip-build-13zxync1/emperor/

What to do next?

**Comment by ElDeveloper** [comment]
I believe you are having a a permissions problem, you may need to ask your system's administrator to help you install this package. Additionally, we recommend that you only install the most recent version:

```
    # with pip
    pip install emperor --pre

    # with conda
    conda install -c conda-forge emperor
```

**Comment by ehossain1982** [comment]
I am on my laptop as admin! But the --pre command solved it.......

Successfully installed CacheControl-0.12.4 emperor-1.0.0b14 future-0.16.0 lockfile-0.12.2 natsort-5.2.0 scikit-bio-0.5.1

**Comment by ehossain1982** [comment]
However, still Plot not opening on safari! Thank you for looking into it.

**Comment by ElDeveloper** [comment]
If you are viewing a plot in your computer, then you don't need to install emperor. Can you try opening the plot in a different browser? What do you see on the screen when you try to open the plot? If you can take a screenshot, that might help diagnose the problem faster.

**Comment by ehossain1982** [comment]
<img width="1325" alt="screen shot 2018-04-04 at 09 19 54 am" src="https://user-images.githubusercontent.com/38051718/38320726-f98a1fa4-37fa-11e8-81ff-68c6294895e4.png">

**Comment by ehossain1982** [comment]
I also opened another ticket on this issue (thinking that no one will check as this one was tagged closed. Sorry for the double issue.)

**Comment by ehossain1982** [comment]
Chrome works.

**Comment by ElDeveloper** [comment]
No worries, let's keep all the messages in this ticket.

I believe the problem is specific to Safari as noted in #610. My suggestion is that you use Google Chrome instead as we won't be able to fix this issue for Safari.
