### ISSUE TITLE
Even after updating Emperor to latest version plots still don't open in Safari on Mac! How to fix it? Thank you.

### ISSUE THREAD

**Issue by ehossain1982** [biocore/emperor#658]
As said in the title: I am attaching a screen shot of the blank safari window that I get.

<img width="1325" alt="screen shot 2018-04-04 at 09 19 54 am" src="https://user-images.githubusercontent.com/38051718/38313414-96e4f060-37e9-11e8-935c-aa6f0c32c6e2.png">

**Comment by ElDeveloper** [comment]
@ehossain1982 This is probably related to #610. I suggest that you either try using Google Chrome or switch to the latest version of Emperor. Note that the plot you have was generated with an old version of emperor (did you use QIIME 1 to do this?).

**Comment by Lyle101** [comment]
Set "Disable local file restrictions" in the Develop menu.
see: [Safari 11 gets SecurityError (DOM exception 18) when accessing localStorage](https://forums.developer.apple.com/thread/87778)
