### ISSUE TITLE
If a PCoA output has null values or zeroes it leads to emperor fails

### ISSUE THREAD

**Issue by Prasanth691** [biocore/emperor#659]
If there's a PcoA table that passed as input of emperor and it has a column where some of the values are zeros, the code will execute  with warnings . but when opening in the browser the following error will come up in the JavaScript console:

Uncaught Error : NaN is not defined
![2018-04-10](https://user-images.githubusercontent.com/11070011/38597203-c0387e12-3d45-11e8-8ce9-c194d919d4a5.png)

**Comment by ElDeveloper** [comment]
Thanks for reporting this @Prasanth691.

This is definitely a bug with the 0.9.x series (it is no longer an issue in 1.x), however in general you shouldn't expect to see NaNs in your ordination results. If you do have NaNs in your ordination, the results are likely invalid. I would suggest tracing back the reason why the NaNs are happening. It is likely a case of an "empty" sample i.e. a sample where all observations are zero.

**Comment by ElDeveloper** [comment]
Feel free to reopen, if you have more questions.
