### ISSUE TITLE
Clarification on usability of new/old versions of Emperor with Qiime 1 and 2

### ISSUE THREAD

**Issue by rmwade** [biocore/emperor#678]
Hello,

I have used Emperor successfully in the past and have included the plots in publications. I am trying to use version 0.9.61 with Qiime 1 (v. MacQIIME 1.9.1-20150604) and ran the script successfully, but cannot visualize the plot with Safari or Chrome - all I see is the emperor logo. Is it no longer possible to visualize plots with the Emperor version I'm using, and/or Qiime1?

The make_emperor.py output is: file:///Users/rachaelwade/Desktop/Airborne/16S/betadiversity_files/biplot/index.html

Thank you for your help!

**Comment by ElDeveloper** [comment]
@rmwade, QIIME 1's emperor i.e. 0.9.x will continue to work (as long as the web technologies underlying that implementation continue to be supported). The output you describe seems incomplete as it should also include a folder named `emperor_required_resources`, without this folder the results cannot be visualized. Please verify that you have this folder.

Feel free to reopen this issue if you continue to see this problem.

**Comment by rmwade** [comment]
Hi Yoshiki,

Thank you for your quick reply. The output did include the folder you
describe (attached), however, I have never had to use this folder in the
past with figures I've generated for publications and am confused how to do
so in conjunction with the .html file. In the past, I've simply opened that
link and been able to see the plot. How do I connect the .html files with
the emperor_required_resources file? Also, if this is new, may I suggest
this be added somewhere, perhaps to the tutorial?

Thank you for your assistance.

Sincerely,

Rachael

**Comment by rmwade** [comment]
Sorry, I did not in fact attach the files:

**Comment by ElDeveloper** [comment]
Thanks for clarifying @rmwade seems like you have everything you need. GitHub won't send attachments when replying via e-mail.

I think this is likely a bug. Would you mind opening the plot and looking at the JavaScript console (copy-pasting the output), this would be done in Google Chrome by going to `View > Developer > JavaScript Console`

**Comment by rmwade** [comment]
Uncaught ReferenceError: nan is not defined
    at index.html:109
three.min.js:520 THREE.WebGLRenderer 68
emperor.js:1827 Uncaught TypeError: Cannot convert undefined or null to
object
    at Function.keys (<anonymous>)
    at changeAxesDisplayed (emperor.js:1827)
    at init (emperor.js:2323)
    at HTMLDocument.<anonymous> (emperor.js:2155)
    at n (jquery-1.7.1.min.js:2)
    at Object.fireWith (jquery-1.7.1.min.js:2)
    at Function.ready (jquery-1.7.1.min.js:2)
    at HTMLDocument.B (jquery-1.7.1.min.js:2)

Thank you!

**Comment by rmwade** [comment]
I used Bray-Curtis.

I looked back at the my OTU table and realized several of my samples were
empty after contaminant removal. This was sloppy on my part, I should have
checked for this. However, I reran make_emperor after removing these empty
samples from the prior steps and am now getting a different error:

Traceback (most recent call last):

  File
"/Users/rachaelwade/Downloads/emperor-0.9.61/scripts/make_emperor.py", line
17, in <module>

    from emperor.qiime_backports.filter import filter_mapping_file

  File
"/macqiime/anaconda/lib/python2.7/site-packages/emperor/__init__.py", line
40, in <module>

    from emperor.core import Emperor

  File "/macqiime/anaconda/lib/python2.7/site-packages/emperor/core.py",
line 35, in <module>

    from skbio import OrdinationResults

ImportError: cannot import name OrdinationResults

Any idea why this error popped up this time and not in the previous run
that ran to completion, and how to fix it?

Thank you!

**Comment by ElDeveloper** [comment]
No worries. I don't have an idea of why this may be happening. Can you 
send the output of pip show scikit-bio

Thanks!

Yoshiki.

**Comment by rmwade** [comment]
Name: scikit-bio

Version: 0.2.3

Summary: Data structures, algorithms and educational resources for
bioinformatics.

Home-page: http://scikit-bio.org

Author: scikit-bio development team

Author-email: gregcaporaso@gmail.com

License: BSD

Location: /macqiime/anaconda/lib/python2.7/site-packages

Requires:

Required-by: qiime, burrito-fillings

**Comment by ElDeveloper** [comment]
Hello,

I think the problem might be that you are using a file named 
make_emperor.py that's located in your Downloads folder i.e. 
/Users/rachaelwade/Downloads/emperor-0.9.61/scripts/make_emperor.py 
however, you are not using the corresponding libraries for 
make_emperor.py. Not sure how you installed version 0.9.61 I would 
recommend not using the installation in your Downloads folder and 
instead using the installation that's bundled with macqiime.

**Comment by rmwade** [comment]
My understanding was that you had to download emperor separately, which is
how I did all of my previous work. When I enter macqiime and use
make_emperor, I get that the message that make_emperor is deprecated. With
all of my troubleshooting, I tried to uninstall and reinstall emperor, but
that seems to be impossible, see error message below:

MacQIIME Rachaels-MacBook-Pro-2:OTU_tables $ pip install emperor==0.9.61

Collecting emperor==0.9.61

  Downloading
https://files.pythonhosted.org/packages/0e/68/8823180d81f6d4181aeaf578d5edeb7fb5cf2befc3447203d22d2e27a7f2/emperor-0.9.61.tar.gz
(3.1MB)

    100% |████████████████████████████████| 3.1MB 1.1MB/s

Requirement already satisfied: numpy>=1.7 in
/macqiime/anaconda/lib/python2.7/site-packages (from emperor==0.9.61)
(1.10.1)

Requirement already satisfied: qcli in
/macqiime/anaconda/lib/python2.7/site-packages (from emperor==0.9.61)
(0.1.1)

Requirement already satisfied: scikit-bio<0.3.0,>=0.2.1 in
/macqiime/anaconda/lib/python2.7/site-packages (from emperor==0.9.61)
(0.2.3)

Installing collected packages: emperor

  Found existing installation: emperor 1.0.0b16.dev0

Cannot uninstall 'emperor'. It is a distutils installed project and thus we
cannot accurately determine which files belong to it which would lead to
only a partial uninstall.

 This may be that it's accessing the other version of make_emperor that I
tried to install, but I can't seem to get rid of it, or access the version
in macqiime. Do you have any suggestions how I can scrub the lingering
versions of emperor and use the macqiime version? I have never been able to
do so.

Thank you!

**Comment by ElDeveloper** [comment]
I see, the newest version of emperor (one that is not compatible with 
QIIME 1.x) is installed. Can you try running these two commands:

pip uninstall emperor
pip install emperor==0.9.61

**Comment by rmwade** [comment]
Hi Yoshiki,

Unfortunately pip uninstall emperor results in the same error:

MacQIIME Rachaels-MacBook-Pro-2:OTU_tables $ pip uninstall emperor

Cannot uninstall 'emperor'. It is a distutils installed project and thus we
cannot accurately determine which files belong to it which would lead to
only a partial uninstall.

**Comment by ElDeveloper** [comment]
I think the next thing that might be worth trying is deleting the folder 
altogether. With 'pip show emperor' see where the "Location" of the 
package is. Go to that folder and delete any emperor-prefixed folders. 
After doing this you'll need to reinstall emperor, make sure you run pip 
install emperor==0.9.61. Note you'll need admin permissions, so be 
careful.

If you don't have a "custom" macqiime installation that would require 
you to redo a lot of additional steps, I would suggest just reinstalling 
macqiime, and running pip install emperor==0.9.61

**Comment by rmwade** [comment]
That worked! I have an emperor PCoA! Thank you so much for all of your time
and continued help with this, I greatly appreciate it.

Sincerely,

Rachael

**Comment by ElDeveloper** [comment]
Great to hear it is working for you.
