### ISSUE TITLE
Usage instruction is missing

### ISSUE THREAD

**Issue by JasonRts** [biocore/emperor#680]
Hi, I followed the "Emperor Installation Notes" in INSTALL.md and installed the latest per-release (v1.0.0-beta.16) using "conda install -c conda-forge emperor". However, it's not explained anywhere how to use it. The "make_emperor.py" file is deprecated, and when I open the example IPython files (e.g. biplot.ipynb) and run the first cell, I get the following error. Could anyone please let me know if I'm doing it wrong, or if there is a document that explains how to use it? I've also tried installing it using pip, as well as running the setup script.

ImportError                               Traceback (most recent call last)
<ipython-input-1-9a2c9fa999b9> in <module>()
      1 import pandas as pd, numpy as np
      2 
----> 3 from emperor import Emperor, nbinstall
      4 
      5 from skbio import OrdinationResults

ImportError: cannot import name nbinstall

**Comment by ElDeveloper** [comment]
@JasonRts, thanks for reaching out and apologies for the delayed response (I just saw this message).

The error seems to be related to conflicting versions of emperor being installed in your system. Were you installing the latests pre-release in an existing QIIME environment? And if so, was this QIIME 1.9.x by chance? Alternatively, it is likely that an old version of Emperor is installed in your system (outside the conda environment) and it is conflicting with this version.

Can you try installing emperor in a new clean environment and checking if the error still persists?

**Comment by ElDeveloper** [comment]
Closing for now. @JasonRts, feel free to re-open.
