### ISSUE TITLE
Safari issue with Emperor Plot

### ISSUE THREAD

**Issue by ehossain1982** [biocore/emperor#685]
I am on safari 11.1.2. In the past, I have an issue where the Emperor plot will not open in safari but will open in Firefox/Chrome. So I was using chrome for my work. Today I found out the following.

Do a google search in Safari using the exact words: "emperor plot working on chrome but not on safari"

The 6th hit from the top....if I click it, the emperor plot opens in safari with no problem. But my own emperor plots will not open in safari.

What am I doing wrong? Thank you.

**Comment by ElDeveloper** [comment]
@ehossain1982 in general we recommend that you use Google Chrome. However, this is definitely puzzling. I think that you may be using an older version of emperor, or at least an older one that the one in the link you found through your google search. Would you mind sending us the output of the command below (where "emperor-plot" is the folder where you have your plot):

```
head emperor-plot/index.html
````

**Comment by ehossain1982** [comment]
This is the output:



<img width="926" alt="image" src="https://user-images.githubusercontent.com/38051718/44241115-83482380-a187-11e8-855b-724822abc733.png">

**Comment by ElDeveloper** [comment]
Thanks @ehossain1982. After some testing, this is a result of the plots being loaded locally, if the plots are loaded from a server, then everything works fine. Hence, why you are able to view plots that are hosted somewhere else (as from your Google search result).

As noted in #610 this is specific to Safari and we won't be able to backport a fix of this to the 0.9.x series. My recommendations are to either use Chrome/Firefox, or to update the version of QIIME you are using. In newer versions of Emperor this is not a problem and everything works well in Safari.

**Comment by ehossain1982** [comment]
I will upgrade to 1.0.0-beta.X then.

One last question: Can the emperor plot be used as a standalone viewer instead of using a browser? Like in jupyter notebook? If so is there a tutorial/documentation for that?

**Comment by ElDeveloper** [comment]
@ehossain1982 sounds good. Just make sure you also update QIIME as Emperor 1.0.0-beta.X is not compatible with QIIME 1.9.x.

Yes, this can be done! If you look [here](https://github.com/biocore/emperor/tree/new-api/examples), you'll find some notebooks with some examples doing this exactly.

**Comment by ehossain1982** [comment]
Thank you.
