### ISSUE TITLE
Unable to move the plot up, down, left, or right 

### ISSUE THREAD

**Issue by stephanieorch** [biocore/emperor#688]
We are able to rotate the plot and zoom in and out however I am unable to drag the plot up and down. This is an issue because sometimes when I load a plot I am only able to see half of the plot so I have to zoom out really far to see all of it. For example, I just loaded a plot and this is what I see (and my page is scrolled all the way to the bottom):

<img width="1436" alt="screen shot 2018-08-21 at 9 36 40 am" src="https://user-images.githubusercontent.com/31080457/44415614-c4448d00-a525-11e8-9ae0-36e1c0eabd1a.png">

**Comment by antgonza** [comment]
You can move left, right, top, down with the right button ... 
![emperor](https://user-images.githubusercontent.com/2014559/44416748-ff988900-a530-11e8-8c60-886592555668.gif)
