### ISSUE TITLE
Installation is failed with a warning

### ISSUE THREAD

**Issue by dfat** [biocore/emperor#699]
Hi expert,

When I tried to verify if the installation with "make_emperor.py -h" , the  following warning is raised:

"This script has been deprecated, please see the online documentation for more help."

Could anyone tell me why? How should I do for installation?

Thanks,
Xin

**Comment by ElDeveloper** [comment]
In the new version of Emperor `make_emperor.py` is no longer available as a script. If you want to use this, I suggest that you downgrade your installation to version 0.9.61. You can do this by running this command:

```
pip install emperor==0.9.61
```
