### ISSUE TITLE
add: -p PREFS_PATH, --prefs_path=PREFS_PATH

### ISSUE THREAD

**Issue by antgonza** [biocore/emperor#7]
Input user-generated preferences filepath. NOTE: This
is a file with a dictionary containing preferences for
the analysis. [default: none]

Notes:
- This will be a good opportunity to revise the parameters file format. Currently is too hard to understand for users.

**Comment by JWDebelius** [comment]
:+1: for this functionality.

It would be nice to have the option of playing an animation as well.
