### ISSUE TITLE
Error: QIIME 2 plugin 'emperor' has no action 'biplot'.

### ISSUE THREAD

**Issue by olsonca** [biocore/emperor#711]
Hello,

I have the following error message for emperor in the biplot functionality:
Error: QIIME 2 plugin 'emperor' has no action 'biplot'.

Do you have any suggestions for how to correct this? Thank you.

Best,
Christine

**Comment by ElDeveloper** [comment]
@olsonca, what version of QIIME2 are you using? It looks like your current version does not have that action (probably pre-august 2018). In that case, the solution would be to install a new version.
