### ISSUE TITLE
export svg arrow and sample legends together

### ISSUE THREAD

**Issue by cameronmartino** [biocore/emperor#712]
First raised [here](https://forum.qiime2.org/t/deicode-visualization-issue-in-qiime2view/9055/4) the biplot arrow and sample legends can be difficult to export as svgs. So it would be nice if both automatically exported when possible.

**Comment by ElDeveloper** [comment]
Thanks for reporting this and for the forum x-ref. This is a duplicate of #634, legends should include both arrows, points, and all their attributes (color, shape, etc).
