### ISSUE TITLE
Animations do not respect Visibility

### ISSUE THREAD

**Issue by sjanssen2** [biocore/emperor#716]
Hi Yoshiki,
if I set visibility of some of my sample to false, trajectories for those are still plotted when I hit play on the wonderful animations. Is this a bug or a feature?

I am using view.qiime2.org (I don't know which version is used there)

**Comment by ElDeveloper** [comment]
As it stands this is a feature, but it is more often perceived as a bug. Hence this issue: https://github.com/biocore/emperor/issues/652. 

I would suggest that as a workaround you could set the "gradient" value for the samples that you don't want to animate as 0. That will eliminate the traces from the plot. Downside is that you will need to modify the "gradient" column.
