### ISSUE TITLE
Axes inversion not saved in settings

### ISSUE THREAD

**Issue by sjanssen2** [biocore/emperor#717]
I just found that the version at view.qiime2.org does **not** save the setting of axes inversion.

**Comment by ElDeveloper** [comment]
Thanks for reporting. I just tried this out using an example visualization in view.qiime2.org and everything seems to work just fine. Here's an animated GIF showing how I can change the orientation, save settings, reload the plot on the browser and then load the saved settings:

![inversion-bug](https://user-images.githubusercontent.com/375307/57644776-b03c3200-7571-11e9-94e8-f65ef4499c51.gif)


Can you send a series of steps to reproduce this bug?

**Comment by sjanssen2** [comment]
Hi @ElDeveloper ,
I haven't found a good tool to make a proper screencast without revealing too many private infos floating around on my desktop. Therefore, I sent you the video via email - I don't want to have it online on github.
The problem is if I invert axis1, save that, play with the other axis, reload the saved settings not everything is reverted back to the status as of the saving time.

**Comment by ElDeveloper** [comment]
Thanks so much for sending the screen capture and steps to reproduce. I have now been able to identify the problem. Looks like there's a problem with how the axes are set after loading the settings file.
