### ISSUE TITLE
Enabling inversion of ordination objects

### ISSUE THREAD

**Issue by mortonjt** [biocore/emperor#732]
The discussion originally started here

https://github.com/qiime2/q2-diversity/issues/258

There are currently two use-cases 

1. Plotting metabolites as arrows and microbes as points with mmvec
2. Plotting microbe co-occurrences with DEICODE

The solution is simple - just swap the points and arrows.

**Comment by ElDeveloper** [comment]
This was fixed here: https://github.com/qiime2/q2-emperor/pull/83
