### ISSUE TITLE
"Cannot read property 'getExtension' of null" three.js error on startup in Chrome

### ISSUE THREAD

**Issue by fedarko** [biocore/emperor#737]
Shi and I ran into this today while trying to load an Emperor QZV file in q2view.

On startup, Emperor just stayed at its splash screen without doing anything. Opening up the Chrome browser console, we saw a bunch of three.js errors (along the lines of [the stuff described in this thread we found from googling the errors](https://github.com/mrdoob/three.js/issues/4927)). That thread made this seem like a browser issue, and sure enough opening up the same visualization in q2view in *Safari* fixed the problem for some weird reason.

This isn't really an Emperor problem -- more of a three.js thing -- but it may be worth adding something to the docs mentioning that if Emperor gets stuck at the splash screen you might want to try another browser. At the very least, if other people run into this problem then hopefully Google leads them to this issue :)

**Comment by ElDeveloper** [comment]
That's odd. If you have a chance, can you post the exact version of Google Chrome that you are using and the OS?

**Comment by ElDeveloper** [comment]
The recent update to THREE.js should help with this issue. If the problem persists we can further look into it.
