### ISSUE TITLE
Parallel plot display looks odd when activated from a biplot, and causes issues in the scatterplot view

### ISSUE THREAD

**Issue by fedarko** [biocore/emperor#747]
Just ran into this today -- figured I should raise an issue here.

## Steps to reproduce

1. Open up a biplot in Emperor. I'm using the biplot produced in [this notebook](https://nbviewer.jupyter.org/github/biocore/qurro/blob/master/example_notebooks/DEICODE_sleep_apnea/deicode_example.ipynb) with [this version of DEICODE](https://github.com/biocore/DEICODE/pull/54), for reference.

<img width="1435" alt="Screen Shot 2020-01-07 at 4 28 24 PM" src="https://user-images.githubusercontent.com/4177727/71940371-ef576d00-316a-11ea-8c75-e037e2437173.png">

2. Switch to `Parallel Plot`.
**Problem 1:** first this shows a zoomed-in view of the parallel plot, which seems odd but not a huge problem.

<img width="1437" alt="Screen Shot 2020-01-07 at 4 30 03 PM" src="https://user-images.githubusercontent.com/4177727/71940403-0d24d200-316b-11ea-8810-8b4969143837.png">

**Problem 2:** However, when you zoom out in the parallel plot view you also see that some of the arrows from the biplot are still hanging around. (My guess is that the presence of these arrows is messing with the camera somehow, but I can't confirm that.)

<img width="1440" alt="Screen Shot 2020-01-07 at 4 30 55 PM" src="https://user-images.githubusercontent.com/4177727/71940445-30e81800-316b-11ea-9601-c1fb85a88c30.png">

3. Switch back from `Parallel Plot` to `Scatter`.
**Problem 3:** For some reason, one of the 3 arrows from the biplot is now missing?

<img width="1439" alt="Screen Shot 2020-01-07 at 4 36 50 PM" src="https://user-images.githubusercontent.com/4177727/71940656-edda7480-316b-11ea-8445-02a30f761d16.png">

## Desired behavior
Ideally:
- The camera should be initialized to show a complete view of the parallel plot
- The parallel plot should not contain the arrows 
- All displayed arrows should be preserved when moving back to the biplot

## Workaround
In practice, if parallel plots will cause lots of problems with biplots, I guess it might make sense to just temporarily disable parallel plots for biplot visualizations -- this way at least users won't run into the above problems (in particular problem 3, which IMO is the most scary). But it's not really my call :)

Thanks!

**Comment by ElDeveloper** [comment]
Thanks for reporting this @fedarko. @dhakim87 do you have some time to look into this issue? Looks like this may have been introduced in #727
