### ISSUE TITLE
Duplicate axis created when using weird axis settings

### ISSUE THREAD

**Issue by fedarko** [biocore/emperor#748]
This seems to me like a pretty obscure problem, but I think it is technically a bug.

## Steps to reproduce

1. Open up a plot or biplot in Emperor (I checked and this error is reproducible with normal scatterplots or biplots)

<img width="1437" alt="Screen Shot 2020-01-07 at 11 16 30 PM" src="https://user-images.githubusercontent.com/4177727/71957959-e767ef00-31a3-11ea-9df1-7f4ee06a31ae.png">

2. Go to the `Axes` tab and set all axes to the same PC (I know, I know). As expected, all of the samples are constrained to a single line in the ordination space.

<img width="1438" alt="Screen Shot 2020-01-07 at 11 18 05 PM" src="https://user-images.githubusercontent.com/4177727/71958025-1e3e0500-31a4-11ea-8a75-78c2d62ed41c.png">

3. Set any of the axes to a different PC. Now, for some reason, the axis display is duplicated:

<img width="1440" alt="Screen Shot 2020-01-07 at 11 20 16 PM" src="https://user-images.githubusercontent.com/4177727/71958090-46c5ff00-31a4-11ea-8d40-f6648d529189.png">

Note that the "direction" of the duplication (wherever the new axis display ends up in relation to the original one) seems to be based on the axis you changed in step 3 -- changing the first axis as shown in the screenshot shifts the duplicate axis horizontally, changing the second axis shifts the duplicate axis vertically (see below), and changing the third axis shifts the duplicate axis "towards the camera" (at least from the default camera settings).

<img width="1438" alt="Screen Shot 2020-01-07 at 11 22 50 PM" src="https://user-images.githubusercontent.com/4177727/71958269-bb00a280-31a4-11ea-9f94-c47eac4f7bef.png">

I don't know _why_ this error happens, but it might have ramifications for other parts of Emperor.

**Comment by ElDeveloper** [comment]
Thanks for reporting @fedarko!

@dhakim87, do you think this could have anything to do with how the axes drawing was reworked in your previous PR? Any chance you can have a look at this?
