### ISSUE TITLE
Display blanks out occasionally

### ISSUE THREAD

**Issue by fedarko** [biocore/emperor#758]
Occasionally, the display will just kind of "blank out" when viewing an ordination:

<img width="1552" alt="Screen Shot 2020-02-21 at 2 20 37 PM" src="https://user-images.githubusercontent.com/4177727/75076534-49ab5380-54b5-11ea-85f5-b0d2e7adf9d9.png">

This will sometimes happen to me when I just do something normal in an open visualization (e.g. moving over to the `Animation` tab, re-scaling a single sample, ...) I'm not sure what exact circumstances trigger this problem, but I have noticed that I can at least reliably reproduce it in the [Q2 moving pictures visualization](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fdocs.qiime2.org%2F2019.10%2Fdata%2Ftutorials%2Fmoving-pictures%2Fcore-metrics-results%2Funweighted_unifrac_emperor.qzv) by starting autorotation, moving to another tab, waiting for a bit (around 20 seconds causes the problem but 10 seconds doesn't -- no idea why), and then toggling back. (That being said I don't think autorotation is a _prerequisite_ for this, since I've observed this happening in other cases.)

When the plot is in its "blanked out" state, interacting with it by e.g. clicking-and-dragging the mouse doesn't seem to fix things -- but I can still double-click on samples to select them, so it seems like the underlying event processing stuff is still being handled.

<img width="1552" alt="Screen Shot 2020-02-21 at 2 26 40 PM" src="https://user-images.githubusercontent.com/4177727/75076874-1b7a4380-54b6-11ea-8463-763589ae327f.png">

Once in the "blanked out" state, I can reliably fix this by opening the dev console (command-alt-i in chrome on mac). I found that using command-shift-B to toggle the bookmarks bar also fixes this, weirdly enough, as does just resizing the browser window -- I'm guessing that the window-resizing action triggers an update to the display somehow that fixes the problem.

<img width="1552" alt="Screen Shot 2020-02-21 at 2 21 19 PM" src="https://user-images.githubusercontent.com/4177727/75076552-5c258d00-54b5-11ea-8d50-7434c44ae11b.png">

(I can't find an open issue for this, which is why I'm making a new one here.)

I've observed this problem in the QIIME 2 2019.10 and 2019.7 versions of Emperor (these are the only versions I've tried to replicate this problem on), on a macOS 10.15.3 laptop with Chrome 79.0.3945.130. Based on talking with Pedro today I also know others in the lab have run into this problem.

**Comment by ElDeveloper** [comment]
With the recent updates to THREE.js I would expect for these issues to not happen anymore. Let's close for now, and feel free to re-open if you see this again.
