### ISSUE TITLE
Error in emperor: Samples missing in final visualization 

### ISSUE THREAD

**Issue by MrX-NGS** [biocore/emperor#778]
Hi,

I find only 23 samples in the final visualization instead of 66 samples. I used the below commands in qiime 1.9.1 conda environment as below with emperor installed in the environment:

make_emperor.py -i binary_jaccard_pc.txt -m map.e500.fmt.fmt.fmt.txt -o final_plot
zip -r emperor_plots.zip emperor_plots

[map.e500.fmt.fmt.fmt.txt](https://github.com/biocore/emperor/files/5000044/map.e500.fmt.fmt.fmt.txt)
[binary_jaccard_pc.txt](https://github.com/biocore/emperor/files/5000045/binary_jaccard_pc.txt)

Any help to solve this visualization error will be useful!
[final_plot.zip](https://github.com/biocore/emperor/files/5000055/final_plot.zip)

**Comment by ElDeveloper** [comment]
@MrX-NGS would you be able to run this using the latest version of QIIME2 and see if the same problem persists? We no longer provide support for QIIME 1.9.1.
