### ISSUE TITLE
Frame is cut when looking at a rarefaction plot in view.qiime

### ISSUE THREAD

**Issue by antgonza** [biocore/emperor#790]
Basically if you open a rarefaction plot and wait for a few seconds and/or start interacting with the zoom; the plot frame gets cut in half, like this:
![rarefaction](https://user-images.githubusercontent.com/2014559/96368738-db399680-1112-11eb-9c45-cef04657914a.gif)

Here is the [original qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fdl.dropbox.com%2Fs%2Fg1g5h8xizpeu21o%2F100985_visualization.qzv%3Fdl%3D1).

**Comment by ElDeveloper** [comment]
Thanks for linking to the artifact! As far as I can tell this is an issue with the q2 template not with Emperor. Seems like the containers for the PCoA, the Heatmap, and the hierarchical tree all have a "partial height".

**Comment by antgonza** [comment]
Thank you for taking a look @ElDeveloper; do we need to move this issue to another repo?

**Comment by ElDeveloper** [comment]
Good call, just opened this issue in q2-diversity
