### ISSUE TITLE
How to draw a 95% confidence ellipse in a Emperor PCoA?

### ISSUE THREAD

**Issue by oseias-r-junior** [biocore/emperor#807]
Hello, 
Is that possible to draw a 95% confidence ellipse around the dots representing a set of samples in Emperor?
I saw some related issues, but it seems also that it stopped being updated a long ago. So, IDK if there is already something new regarding this topic.

If so, is there an example/pipeline that someone can follow on how to include it in a given PCoA made in Emperor?
Thanks in advance!

**Comment by antgonza** [comment]
You are looking for https://docs.qiime2.org/2021.11/plugins/available/diversity/beta-rarefaction/.

**Comment by oseias-r-junior** [comment]
Sorry, saw that you closed the issue, but your answer hasn't actually solved my question.

I mean a 95 % confidence interval in a 3D PCoA (like [here](https://nbviewer.org/github/biocore/emperor/blob/new-api/examples/keyboard.ipynb)), also, I was thinking of an example for a jupyter notebook? BTW, the link you sent seems to be outdated or not supported anymore.

**Comment by ElDeveloper** [comment]
If you have a set of ordinations for which you would like to draw ellipses around a reference ordination. You can use the jackknifing API as shown in this notebook:
https://nbviewer.org/github/biocore/emperor/blob/new-api/examples/jackknifed.ipynb

Through the notebook API you can select different methods to draw these ellipses i.e. `IQR` for interquartile range, `ideal_fourths` for quartiles based on the ideal fourths method, and `sdev` for standard deviation.

The document @antgonza linked to, shows the QIIME2 pipeline to compute ellipses for ordinations resulting from multiple rarefactions at the same sequencing depth. Here's the latest version of this URL:
https://docs.qiime2.org/2022.2/plugins/available/diversity/beta-rarefaction/
