### ISSUE TITLE
De-select all option in emperor

### ISSUE THREAD

**Issue by ekunselman** [biocore/emperor#813]
When selecting a "category" for visualization in Emperor, would it be possible to add a "deselect all" option? I created an PCoA biplot using a collapsed taxonomy, rarefied, relative abundance table, but the biplot shows way too many taxa and the plot is really messy, so I would like a quick way to remove all of the arrows and just select the most important ones.

Alternatively, would it be possible to add a parameter in Qiita pcoa_biplot that asks for the number of features (number of arrows) to display? This would also help clean up the biplot.
<img width="1088" alt="220485116-e38dc312-a320-434a-afce-2c224dce62c0" src="https://user-images.githubusercontent.com/56281882/220489083-a18c9a7b-80a8-44f8-8490-f75b35a544fd.png">

**Comment by ElDeveloper** [comment]
@ekunselman this was added a few months ago, however this new feature hasn't been added to a release therefore it hasn't made it's way to QIIME2 nor Qiita. Here's a link if you are curious about how this looks:
https://github.com/biocore/emperor/pull/806

As for the request about the number of arrows, I've opened a separate ticket in Qiita 🐾 https://github.com/qiita-spots/qiita/issues/3255
